"""
Generate individual Rebel Route text files from ZwiftInsider data.
Source: https://zwiftinsider.com/rebel-routes/
Each file contains: metadata, start route, turn-by-turn directions, Strava link.
"""
import os
import re

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

ROUTES = [
    {
        "name": "Big Ring Little Ring",
        "world": "Watopia",
        "distance": "20.6 km",
        "elevation": "143 m",
        "start_route": "Volcano Flat",
        "strava": "https://www.strava.com/segments/40906313",
        "description": "A short loop covering the Volcano circuit and downtown Watopia.",
        "turns": [
            "1. Left to Ocean Blvd",
            "2. Straight (Right) to Ocean Blvd",
            "3. Straight (Right) to Italian Villas",
            "4. Straight (Right) to Italian Villas",
            "5. Left to Italian Villas",
            "6. Left to Volcano Circuit",
            "7. Straight (Left) to Volcano Circuit",
            "8. Straight (Right) to Volcano KOM",
            "9. Left to Volcano Circuit",
            "10. Straight (Right) to Volcano",
            "11. Left to Downtown",
            "12. Left to Downtown",
            "13. Straight (Right) to KOM",
            "14. Straight (Left) to KOM",
            "15. Straight (Left) to Bridge",
            "16. Straight (Left) to Islands",
            "17. Straight (Right) to Italian Villas",
            "18. Right to Sprint",
            "19. Straight (Left) to Sprint",
            "20. Right to Downtown",
        ],
        "notes": "Also has reverse segment: https://www.strava.com/segments/40906329",
    },
    {
        "name": "Canyon to Cavern",
        "world": "Makuri Islands",
        "distance": "13.41 km",
        "elevation": "87 m",
        "start_route": "Turf N Surf (then U-Turn, left toward Urukazi)",
        "strava": "https://www.strava.com/segments/33397045",
        "description": "Shortest loop covering both the slot canyon (Yumezi-Urukazi) and the cavern (Neokyo-Urukazi) connector roads. Starts/ends at Tidepool Sprint banner.",
        "turns": [
            "1. Straight/Right to Yumezi",
            "2. Right to Neokyo",
            "3. Straight/Right to Tower",
            "4. Straight/Right to Tower",
            "5. Right to Harbor",
            "6. Right to Harbor",
            "7. Right to Urukazi",
            "8. Right to Hidden Reefs",
        ],
        "notes": "Pro tip: once you reach the Tidepool Sprint, just stay right at every turn!",
    },
    {
        "name": "Cliffside Epic Double",
        "world": "Watopia",
        "distance": "52.71 km",
        "elevation": "991 m",
        "start_route": "Mountain Route",
        "strava": "https://www.strava.com/segments/31849910",
        "description": "A figure-8 route climbing the Epic KOM in both directions, using the Epic KOM Bypass road. No Radio Tower climb.",
        "turns": [
            "1. Left to Ocean Blvd",
            "2. Straight to Ocean Blvd",
            "3. Left to Epic KOM",
            "4. Straight to Epic KOM",
            "5. Right to Epic KOM Bypass",
            "6. Left to Reverse Epic KOM",
            "7. Straight to KOM Descent",
            "8. Straight to Sequoia Circle",
            "9. Straight to Sequoia Circle",
            "10. Left to Italian Villas",
            "11. Left to Jungle/Epic KOM",
            "12. Left to Epic KOM Bypass",
            "13. Right to Epic KOM",
            "14. Straight to KOM Descent",
            "15. Straight to Italian Villas",
            "16. Left to Italian Villas",
            "17. Left to Italian Villas",
            "18. Left to Volcano Circuit",
            "19. Straight to Volcano Circuit",
            "20. Left to Volcano Circuit",
            "21. Left to Downtown",
            "22. Left to Downtown",
        ],
    },
    {
        "name": "Dirty Temple KOM Loop",
        "world": "Makuri Islands",
        "distance": "4.37 km",
        "elevation": "75 m",
        "start_route": "Sea to Tree",
        "strava": "https://www.strava.com/segments/31415608",
        "description": "All-dirt loop with repeated partial climbs of the Temple KOM. Great for VO2 intervals (~1.5 km climbing per lap). Use a gravel bike! Lead-in: 3.2 km / 106 m.",
        "turns": [
            "1. Right to Fishing Village",
            "2. Right to Forest Climb",
        ],
        "lead_in": 3.2,
    },
    {
        "name": "Down Up Down",
        "world": "Watopia",
        "distance": "49.35 km",
        "elevation": "1257 m",
        "start_route": "Flat Route",
        "strava": "https://www.strava.com/segments/24393519",
        "description": "Travel from Watopia's lowest point (Ocean Blvd, -5m) to the highest (Alpe du Zwift, 1047m) and back. Must be level 6+.",
        "turns": [
            "1. Left to Ocean Blvd",
            "2. Straight to Ocean Blvd",
            "3. Straight to Italian Villas",
            "4. Left to Jungle/Epic KOM",
            "5. Right to Jungle/Alpe",
            "6. Right to Jungle/Alpe",
            "7. Straight (Right) to Mayan Loop",
            "8. Right to Alpe du Zwift",
            "9. Left to Mayan Loop Rev",
            "10. Straight (Left) to Mayan Loop Rev",
            "11. Left to Epic KOM",
            "12. Left to Italian Village",
            "13. Right to Sequoia Circle",
            "14. Straight to Downtown",
            "15. Straight to Downtown",
            "16. Right to Downtown",
        ],
    },
    {
        "name": "Epic Loop",
        "world": "Watopia",
        "distance": "14.4 km",
        "elevation": "378 m",
        "start_route": "Mountain Route (ride up to Epic KOM banner first)",
        "strava": "https://www.strava.com/segments/31415150",
        "description": "A climber's dream loop: descend the Epic KOM Reverse, cut across the Bypass, climb the Epic KOM forward. Great for ~20min sweetspot intervals. Lead-in: 14.3 km / 433 m.",
        "turns": [
            "1. Right (Straight) to KOM Descent",
            "2. Right to Epic KOM Bypass",
            "3. Right to Epic KOM",
        ],
        "lead_in": 14.3,
    },
    {
        "name": "Fower Power",
        "world": "Scotland",
        "distance": "19.74 km",
        "elevation": "214 m",
        "start_route": "City and the Sgurr",
        "strava": "https://www.strava.com/segments/34255076",
        "description": "A Scotland rebel route exploring the Sgurr and Glasgow areas.",
        "turns": [
            "1. Left to Glasgow",
            "2. Right to Sgurr Summit",
            "3. Left to Sgurr Summit",
            "4. Left to Cliffs",
            "5. Left to Sgurr Summit",
            "6. Right to Tower",
            "7. Left to Cliffs",
            "8. Left to Cliffs",
            "9. Left to Sgurr Summit",
            "10. Left to Tower",
            "11. Straight (Right) to Tower",
            "12. Left to Glasgow",
            "13. Left to Tower",
        ],
    },
    {
        "name": "Hilly KOM Bypass",
        "world": "Watopia",
        "distance": "2.5 km",
        "elevation": "31 m",
        "start_route": "Hilly Route",
        "strava": "https://www.strava.com/segments/26791932",
        "description": "A very short loop using the KOM bypass road on the Hilly Route.",
        "turns": [
            "1. Straight (Right) to KOM",
            "2. Straight (Left) to KOM",
            "3. Right to KOM Bypass",
            "4. Right to KOM",
        ],
    },
    {
        "name": "KOMonster",
        "world": "Watopia",
        "distance": "99.8 km",
        "elevation": "2570 m",
        "start_route": "Hilly Route",
        "strava": "https://www.strava.com/segments/21645117",
        "description": "A massive Watopia route covering nearly every KOM and many key roads. Finishes with Alpe du Zwift.",
        "turns": [
            "1. Straight to KOM",
            "2. Straight (Left) to KOM",
            "3. Straight (Left) to Bridge",
            "4. Straight to Italian Village/Sprint",
            "5. Left to Sequoia Circle",
            "6. Right to Jungle/Epic KOM",
            "7. Straight to Epic KOM",
            "8. Straight to KOM Descent",
            "9. Straight to Sequoia Circle",
            "10. Right to Desert Flats",
            "11. Left to Titans Grove",
            "12. Left to Ocean Blvd",
            "13. Right to Downtown",
            "14. Right to Downtown",
            "15. Right to Volcano Circuit",
            "16. Right to Volcano Circuit CCW",
            "17. Straight to Volcano KOM",
            "18. Straight to Volcano Circuit CCW",
            "19. Straight to Italian Villas",
            "20. Right to 360 Bridge",
            "21. Straight to 360 Bridge",
            "22. Straight to Reverse KOM",
            "23. Straight (Right) to Reverse KOM",
            "24. Straight (Right) to Downtown",
            "25. Right to Ocean Blvd",
            "26. Left to Desert Flats",
            "27. Right to Titans Grove",
            "28. Right to Epic KOM",
            "29. Left to Epic KOM",
            "30. Straight to EPIC KOM",
            "31. Straight to KOM Descent",
            "32. Left to Jungle/Alpe",
            "33. Right to Jungle/Alpe",
            "34. Straight (Right) to Mayan Loop",
            "35. Right to Alpe du Zwift",
        ],
    },
    {
        "name": "Litus Fugit",
        "world": "Watopia",
        "distance": "61 km",
        "elevation": "269 m",
        "start_route": "The Big Ring",
        "strava": "https://www.strava.com/segments/35852231",
        "description": "A flat-ish Watopia route covering the southern coast, Mayan roads, jungle, and desert.",
        "turns": [
            "1. Left to Southern Coast",
            "2. Right to Southern Coast",
            "3. Right to Mayan Loop",
            "4. Left to Mayan Bridge",
            "5. Left to Mayan Loop",
            "6. Straight (Left) to Jungle Loop",
            "7. Right to Southern Coast",
            "8. Right to Desert Flats",
            "9. Straight (Right) to Desert Turnaround",
        ],
    },
    {
        "name": "Mangrove Circuit",
        "world": "Makuri Islands",
        "distance": "1.88 km",
        "elevation": "13 m",
        "start_route": "Island Hopper",
        "strava": "https://www.strava.com/segments/33397094",
        "description": "A very short circuit through the mangrove maze. Great for short efforts.",
        "turns": [
            "1. Right to Mangrove Maze South",
            "2. Left to Mangrove Maze North",
            "3. Left to Mangrove Maze South",
        ],
        "notes": "Pro tip: just stay left after the first right turn!",
    },
    {
        "name": "Nessie's Loop",
        "world": "Scotland",
        "distance": "1.89 km",
        "elevation": "15 m",
        "start_route": "Loch Loop (then U-Turn)",
        "strava": "https://www.strava.com/segments/34255208",
        "description": "A tiny Scotland loop around the loch area.",
        "turns": [
            "1. U-Turn",
            "2. Straight (Left) to Tower (lead-in)",
            "3. Right to Cliffs",
            "4. Right to Tower",
        ],
    },
    {
        "name": "Sgurr 8",
        "world": "Scotland",
        "distance": "12.62 km",
        "elevation": "150 m",
        "start_route": "Rolling Highlands (then U-Turn after lap banner)",
        "strava": "https://www.strava.com/segments/34485671",
        "description": "A figure-8 route around Scotland's Sgurr area.",
        "turns": [
            "1. Right to Glasgow",
            "2. Right to Glasgow",
            "3. Right to Sgurr Summit",
            "4. Left to Cliffs",
            "5. Left to Sgurr Summit",
            "6. Left to Sgurr Summit",
            "7. Right to Tower",
        ],
    },
    {
        "name": "Summit City Velodrome",
        "world": "Watopia",
        "distance": "2.53 km",
        "elevation": "0 m",
        "start_route": "Oh Hill No (then U-Turn)",
        "strava": "https://www.strava.com/segments/37626854",
        "description": "10 laps of Ciudad La Cumbre roundabout CCW. First prompt defaults correct (left to Radio Tower), second prompt needs manual straight toward Jungle Ruins.",
        "turns": [
            "1. Left to Radio Tower (default — correct)",
            "2. Straight toward Jungle Ruins (manual — override default)",
            "   Repeat for 10 laps of the roundabout",
        ],
    },
    {
        "name": "The Full Makuri",
        "world": "Makuri Islands",
        "distance": "80.9 km",
        "elevation": "650 m",
        "start_route": "Two Village Loop",
        "strava": "https://www.strava.com/segments/40661737",
        "description": "Covers every road in Makuri Islands across all three zones (Yumezi, Neokyo, Urukazi).",
        "turns": [
            "1. Right to Farmlands",
            "2. Left to Village Onsen",
            "3. Right to Village Onsen",
            "4. Straight to Village Onsen",
            "5. Right to Village Gardens",
            "6. Straight to Village Shops",
            "7. Left to Fishing Village",
            "8. Right to Castle Path",
            "9. Right to Castle Path",
            "10. Straight (Left) to Marketplace",
            "11. Straight (Left) to Marketplace",
            "12. Left to Forest Climb",
            "13. Left to Fishing Village",
            "14. Left to Fishing Village",
            "15. Left to Castle Path",
            "16. Right to Village Onsen",
            "17. Right (to Fishing Village)",
            "18. Left to Forest Climb",
            "19. Straight (Left) to Forest Climb",
            "20. Straight (Left) to Castle Path",
            "21. Straight (Left) to Marketplace",
            "22. Left to Castle Outskirts",
            "23. Right to Forest Road",
            "24. Straight (Left) to Forest Road",
            "25. Straight (Right) to Village Onsen",
            "26. Left to Rice Paddies",
            "27. Right to Neo Tower",
            "28. Straight (Left) to Neokyo",
            "29. Straight (Right) to Tower",
            "30. Straight (Right) to Tower",
            "31. Right to Harbor",
            "32. Left to Downtown",
            "33. Left to Downtown",
            "34. Right to Sky Lane",
            "35. Straight (Left) to Harbor",
            "36. Straight (Right) to Downtown",
            "37. Left to Arcade",
            "38. Straight (Right) to Arcade",
            "39. Left to Tower",
            "40. Right to Rice Paddies",
            "41. Right to Arcade",
            "42. Left to Downtown",
            "43. Left to Railway",
            "44. Left to Railway East",
            "45. Right to Rooftop",
            "46. Right to Railway East",
            "47. Left to Downtown",
            "48. Left to Downtown",
            "49. Straight (Right) to Castle Park",
            "50. Straight (Left) to Castle Park",
            "51. Right to Harbor",
            "52. Left to Urukazi",
            "53. Straight (Left) to Mangrove Maze",
            "54. Right to Mangrove Maze North",
            "55. Right to Festival Harbor",
            "56. Right to Festival Harbor North",
            "57. Right to Mech Isle",
            "58. Right to Mech Isle South",
            "59. Right to Hidden Reefs",
            "60. Right to Hidden Reefs",
            "61. Right to Mangrove Maze",
            "62. Left to Mangrove Maze South",
            "63. Left to Festival Harbor",
            "64. Left to Festival Harbor South",
            "65. Left to Mech Isle",
            "66. Left to Mech Isle North",
            "67. Left to Hidden Reefs",
            "68. Left to Yumezi",
            "69. Left to Yumezi",
            "70. Right to Farmland",
            "71. Straight (Right) to Castle Path",
            "72. Straight (Left) to Forest Road",
            "73. Right to Castle Path",
            "74. Right to Marketplace",
            "75. Right to Castle Outskirts",
            "76. Straight (Right) to Castle Outskirts",
            "77. Straight (Left) to Farmlands",
        ],
    },
    {
        "name": "The Full New York",
        "world": "New York",
        "distance": "57.8 km",
        "elevation": "596 m",
        "start_route": "The Highline",
        "strava": "https://www.strava.com/segments/40678671",
        "description": "Covers every road in New York across Central Park, city rooftops, bridges, and Prospect Park.",
        "turns": [
            "1. Right to Sky Loop",
            "2. Left to Sky Loop",
            "3. Straight (Right) to KOM Arch",
            "4. Left to KOM Arch",
            "5. Straight (Left) to KOM Arch",
            "6. Left to Park Loop",
            "7. Left to Park Loop",
            "8. Left to Park Loop",
            "9. Left to Park Loop",
            "10. Left to Bethesda Plaza",
            "11. Right to Park Loop Reverse",
            "12. Right to The Baseball Fields",
            "13. Left to Park Loop",
            "14. Left to Park Loop",
            "15. Straight (Right) to Sky Loop",
            "16. Straight (Right) to Sky Loop",
            "17. Left to Sky Loop",
            "18. Straight (Right) to City Rooftops",
            "19. Straight (Right) to Park Loop",
            "20. Left to Park Loop",
            "21. Left to The Baseball Fields",
            "22. Right to Park Loop Reverse",
            "23. Right to Bethesda Plaza",
            "24. Left to Park Loop",
            "25. Straight (Right) to Park Loop",
            "26. Right to Times Square",
            "27. Straight (Left) to Manhattan Bridge",
            "28. Left to Times Square Circuit",
            "29. Right to Manhattan Bridge",
            "30. Right to Manhattan Bridge",
            "31. Straight (Left) to Manhattan Bridge",
            "32. Right to Brooklyn Bridge",
            "33. Right to Manhattan Bridge",
            "34. Straight (Left) to Prospect Park",
            "35. Right to Prospect Park",
            "36. Left to Peristyle Sprint",
            "37. Right to Central Dr",
            "38. Left to Prospect Park Loop",
            "39. Left to Central Dr",
            "40. Right to Brooklyn Bridge",
            "41. Left to Brooklyn Bridge",
            "42. Left to Prospect Park",
            "43. Right to Prospect Park",
            "44. Left to Peristyle Sprint",
        ],
    },
    {
        "name": "The Full Watopia",
        "world": "Watopia",
        "distance": "154.5 km",
        "elevation": "2852 m",
        "start_route": "Oh Hill No",
        "strava": "https://www.strava.com/segments/40760759",
        "description": "Covers every road in Watopia in a single ride. The ultimate Watopia challenge.",
        "turns": [
            "1. Straight (Right) to Radio Tower",
            "2. Straight to Radio Tower",
            "3. Left to Bonus Climb",
            "4. Left to Islands/Jungle",
            "5. Straight to Italian Villas",
            "6. Right to Sequoia Circle",
            "7. Straight (Right) to Epic KOM",
            "8. Right to Epic KOM Bypass",
            "9. Straight to Jungle/Alpe",
            "10. Left to Jungle Reverse",
            "11. Right to Mayan Bridge",
            "12. Left to Mayan Loop",
            "13. Straight (Left) to Jungle Loop",
            "14. Right to Ciudad La Cumbre",
            "15. Straight (Right) to Ciudad La Cumbre",
            "16. Straight (Right) to Fuego Flats",
            "17. Straight (Left) to Fuego Flats",
            "18. Left to Epic KOM",
            "19. Straight (Right) to Epic KOM",
            "20. Right to Titans Grove",
            "21. Straight (Right) to Ocean Blvd",
            "22. Left to Ocean Blvd",
            "23. Right to Downtown",
            "24. Left to KOM",
            "25. Right to KOM Bypass",
            "26. Right to Bridge",
            "27. Right to Italian Villas/Sprint",
            "28. Right to Sprint",
            "29. Left to Volcano Circuit",
            "30. Left to Volcano Circuit",
            "31. Left to Italian Villas",
            "32. Right to 360 Bridge",
            "33. Straight (Left) to 360 Bridge",
            "34. Straight (Right) to Reverse KOM",
            "35. Straight (Right) to Reverse KOM",
            "36. Straight (Right) to Downtown",
            "37. Straight (Left) to Downtown",
            "38. Right to Volcano Circuit",
            "39. Right to Volcano Circuit CCW",
            "40. Straight (Left) to Volcano Circuit CCW",
            "41. Straight (Left) to Volcano KOM",
            "42. Straight (Left) to Volcano Circuit CCW",
            "43. Right to Jarvis Island",
            "44. Right to Jarvis Island Counter",
            "45. Right to Volcano Circuit",
            "46. Right to Volcano Circuit",
            "47. Straight (Right) to Italian Villas",
            "48. Left to Sprint",
            "49. Right to Bridge/Islands",
            "50. Right to Islands",
            "51. Left to Islands",
            "52. Straight (Left) to Sequoia Circle",
            "53. Straight (Left) to Downtown",
            "54. Right to Desert Flats",
            "55. Straight (Left) to Desert Flats",
            "56. Straight (Right) to Epic KOM",
            "57. Left to Epic KOM",
            "58. Left to Epic KOM",
            "59. Straight (Left) to Epic KOM",
            "60. Left to Ciudad La Cumbre",
            "61. Right to Jungle Ruins",
            "62. Right to Jungle Ruins",
            "63. Right to Mayan Loop",
            "64. Straight (Right) to Mayan Loop",
            "65. Straight (Left) to Jungle Loop",
            "66. Straight (Right) to Mayan Loop",
            "67. Right to Alpe du Zwift",
        ],
    },
    {
        "name": "The Marvelous Metric",
        "world": "Watopia",
        "distance": "102 km",
        "elevation": "489 m",
        "start_route": "Mountain Mash",
        "strava": "https://www.strava.com/segments/40883256",
        "description": "A metric century covering many Watopia roads — climbs, flats, and volcano.",
        "turns": [
            "1. Straight to Epic KOM Bypass",
            "2. Left to Sequoia Circle",
            "3. Straight (Left) to Sequoia Circle",
            "4. Right to Downtown",
            "5. Right to Desert Flats",
            "6. Straight (Left) to Desert Flats",
            "7. Left to Ciudad La Cumbre",
            "8. Right to Ciudad La Cumbre",
            "9. Straight (Left) to Jungle Ruins",
            "10. Straight (Left) to Jungle Ruins",
            "11. Right to Mayan Loop",
            "12. Left to Mayan Bridge",
            "13. Left to Mayan Loop",
            "14. Straight (Left) to Jungle Loop",
            "15. Right to Ciudad La Cumbre",
            "16. Straight (Right) to Ciudad La Cumbre",
            "17. Straight (Right) to Fuego Flats",
            "18. Straight (Left) to Fuego Flats",
            "19. Left to Epic KOM",
            "20. Straight (Right) to Epic KOM",
            "21. Left to Epic KOM",
            "22. Right to Sequoia Circle",
            "23. Left to Italian Villas",
            "24. Straight (Right) to Italian Villas",
            "25. Left to Italian Villas",
            "26. Left to Volcano Circuit",
            "27. Straight (Left) to Volcano Circuit",
            "28. Straight (Right) to Volcano KOM",
            "29. Left to Volcano Circuit",
            "30. Straight (Right) to Volcano",
            "31. Left to Downtown",
            "32. Left to Downtown",
            "33. Left to Ocean Blvd",
            "34. Straight (Right) to Ocean Blvd",
            "35. Left to Epic KOM",
            "36. Left to Desert Flats",
            "37. Right to Desert Flats",
            "38. Straight (Left) to Desert Flats",
            "39. Left to Downtown",
            "40. Straight (Right) to Ocean Blvd",
            "41. Right to Downtown",
            "42. Right to Downtown",
            "43. Straight (Left) to Sprint",
            "44. Right to Volcano Circuit",
            "45. Right to Volcano Circuit CCW",
        ],
    },
    {
        "name": "The Perimeter",
        "world": "Watopia",
        "distance": "82.3 km",
        "elevation": "1874 m",
        "start_route": "Bigger Loop",
        "strava": "https://www.strava.com/segments/20483387",
        "description": "Ride the outer edge of Watopia including Bonus Climb and Alpe du Zwift. Most turns auto-navigate; only a few manual turns needed.",
        "turns": [
            "1. Most turns auto-navigate from Bigger Loop",
            "2. 24.6 km: Left to Bonus Climb (after Epic KOM banner)",
            "3. 27.5 km: Left (descending from Bonus Climb)",
            "4. 37.2 km: Right to Alpe du Zwift (after descending Mayan jungle)",
            "5. 63.7 km: Right to Jungle Loop (after Alpe descent)",
        ],
    },
    {
        "name": "The Roads Less Traveled",
        "world": "Watopia",
        "distance": "53.6 km (+5.7 km lead-in)",
        "elevation": "437 m",
        "start_route": "Sugar Cookie",
        "lead_in": 5.7,
        "strava": "https://www.strava.com/segments/35861978",
        "description": "Covers many of Watopia's less-used roads including the bypass, 360 bridge, and jungle paths.",
        "turns": [
            "1. Right to Jungle/Alpe",
            "2. Straight (Right) to Mayan Loop",
            "3. Straight (Left) to Jungle Loop",
            "4. Right to Southern Coast",
            "5. Left to Epic KOM",
            "6. Straight (Right) to Epic KOM",
            "7. Right to Titans Grove",
            "8. Left to Ocean Blvd",
            "9. Right to Downtown",
            "10. Left to KOM",
            "11. Right to KOM Bypass",
            "12. Right to Bridge",
            "13. Right to Italian Villas/Sprint",
            "14. Left to Italian Villas/Sprint",
            "15. Straight (Left) to 360 Bridge",
            "16. Right to Sequoia Circle",
            "17. Straight (Left) to Sequoia Circle",
            "18. Right to Epic KOM",
            "19. Straight (Right) to Epic KOM",
            "20. Right to Epic KOM Bypass",
            "21. Straight to Jungle/Alpes",
            "22. Left to Jungle Reverse",
            "23. Right to Mayan Bridge",
            "24. Left to Mayan Loop",
            "25. Straight (Left) to Jungle Loop",
        ],
    },
    {
        "name": "The Snake",
        "world": "Watopia",
        "distance": "77.4 km",
        "elevation": "661 m",
        "start_route": "Tempus Fugit",
        "strava": "https://www.strava.com/segments/22313236",
        "description": "A long, winding Watopia route covering Desert Flats, Epic KOM, Volcano, 360 Bridge, and more.",
        "turns": [
            "1. Straight (Right) to Epic KOM",
            "2. Right to Titans Grove",
            "3. Left to Ocean Blvd",
            "4. Left to Ocean Blvd",
            "5. Straight to Italian Villas",
            "6. Straight (Right) to Italian Villas",
            "7. Right to 360 Bridge",
            "8. Straight (Right) to Reverse KOM",
            "9. Straight (Right) to Reverse KOM",
            "10. Straight (Right) to Downtown",
            "11. Straight (Left) to Downtown",
            "12. Straight (Left) to Sprint",
            "13. Right to Volcano Circuit",
            "14. Straight (Left) to Volcano Circuit",
            "15. Straight (Right) to Volcano KOM",
            "16. Straight (Left) to Volcano Circuit CCW",
            "17. Straight (Right) to Italian Villas",
            "18. Left to Sprint",
            "19. Straight (Left) to Sprint",
            "20. Right to Downtown",
            "21. Straight (Right) to KOM",
            "22. Straight (Left) to KOM",
            "23. Straight (Left) to Bridge",
            "24. Straight (Left) to Italian Village/Sprint",
            "25. Left to Sequoia Circle",
            "26. Straight (Left) to Sequoia Circle",
            "27. Straight (Left) to Downtown",
            "28. Right to Desert Flats",
            "29. Right to Titans Grove",
            "30. Straight (Left) to Desert Flats",
        ],
    },
    {
        "name": "Toutes les Routes",
        "world": "France",
        "distance": "104.8 km",
        "elevation": "1968 m",
        "start_route": "Casse-Pattes",
        "strava": "https://www.strava.com/segments/24982012",
        "description": "Covers every road in France including Ventoux summit and Mont Saint-Michel.",
        "turns": [
            "1. Straight to Mont Saint-Michel (lead-in)",
            "2. 16 km: Straight to Ventoux Summit",
            "3. 19 km: Right to Mont Saint-Michel",
            "4. 22.5 km: Right to Balloon Field",
            "5. 30 km: Straight to Aqueduct",
            "6. 46.5 km: Straight to Ventoux Summit",
            "7. 50 km: Left to Aqueduct",
            "8. 53 km: Left to Balloon Fields",
            "9. 60.5 km: Left to Ventoux Summit",
            "10. 64 km: Straight to Ventoux Summit",
            "11. 101 km: Straight to Mont Saint-Michel",
            "12. 104.3 km: Straight to Mont Saint-Michel",
        ],
    },
    {
        "name": "Urukazi Flats",
        "world": "Makuri Islands",
        "distance": "7.51 km",
        "elevation": "22 m",
        "start_route": "Bridges and Boardwalks",
        "strava": "https://www.strava.com/segments/33396865",
        "description": "A flat loop around Urukazi covering the festival harbor, mangrove maze, and mech isle areas.",
        "turns": [
            "1. Right to Festival Harbor",
            "2. Left to Festival Harbor South",
            "3. Left to Mangrove Maze",
            "4. Right to Mangrove Maze South",
            "5. Right to Neokyo",
            "6. Left to Hidden Reefs",
            "7. Left to Mech Isle",
            "8. Right to Mech Isle North",
        ],
    },
    {
        "name": "Big Ring Little Ring Reverse",
        "world": "Watopia",
        "distance": "20.6 km",
        "elevation": "143 m",
        "start_route": "Hilly Route",
        "strava": "https://www.strava.com/segments/40906329",
        "description": "The reverse version of Big Ring/Little Ring. Start with Hilly Route ('Little Ring' first), then Volcano Circuit ('Big Ring'). First Rebel Route with an official reverse variant on VeloViewer.",
        "turns": [
            "1. Straight (Right) to KOM",
            "2. Straight (Left) to KOM",
            "3. Right to KOM Bypass",
            "4. Right to KOM",
            "5. Left to Ocean Blvd",
            "6. Straight (Right) to Ocean Blvd",
            "7. Straight (Right) to Italian Villas",
            "8. Straight (Right) to Italian Villas",
            "9. Left to Italian Villas",
            "10. Left to Volcano Circuit",
            "11. Straight (Left) to Volcano Circuit",
            "12. Straight (Right) to Volcano KOM",
            "13. Left to Volcano Circuit",
            "14. Straight (Right) to Volcano",
            "15. Left to Downtown",
        ],
        "notes": "Reverse of Big Ring/Little Ring. Forward version: https://www.strava.com/segments/40906313. Verify turn prompts in-game.",
    },
    {
        "name": "Route 25 Unpublished",
        "world": "Unknown (likely Watopia)",
        "distance": "TBD",
        "elevation": "TBD",
        "start_route": "TBD",
        "strava": "TBD (segment exists on VeloViewer but not published)",
        "description": "This route exists on VeloViewer Rebel Routes leaderboard but has not been published on ZwiftInsider yet. Eric mentioned 'two other Rebel Routes I haven't published yet' on Feb 12, 2026. One was Big Ring/Little Ring (Feb 17). The other remains unpublished as of Feb 23, 2026.",
        "turns": [
            "TBD — check https://zwiftinsider.com/rebel-routes/ for updates",
        ],
    },
]


def parse_distance_km(dist_str):
    """Extract numeric km value from distance string."""
    match = re.search(r'([\d.]+)\s*km', dist_str)
    return float(match.group(1)) if match else 0.0


def estimate_turn_kms(total_km, n_turns, lead_in_km=0):
    """Distribute approximate km values proportionally across turns."""
    if n_turns == 0:
        return []
    if n_turns == 1:
        return [round(lead_in_km + total_km * 0.5, 1)]
    ride_total = lead_in_km + total_km
    first = round(lead_in_km + max(0.3, total_km * 0.03), 1)
    last = round(ride_total * 0.97, 1)
    return [round(first + (last - first) * i / (n_turns - 1), 1) for i in range(n_turns)]


def turn_has_km(turn_text):
    """Check if a turn already has an explicit km or mile marker."""
    return bool(re.search(r'\d+\.?\d*\s*km:|At\s+\d+\.?\d*\s*mi:', turn_text))


def write_route_file(route: dict) -> str:
    """Write a single route file and return its path."""
    safe_name = route["name"].replace("/", "-").replace(" ", "_")
    filename = f"{safe_name}.txt"
    filepath = os.path.join(OUTPUT_DIR, filename)

    lines = []
    lines.append(f"{'=' * 60}")
    lines.append(f"  REBEL ROUTE: {route['name'].upper()}")
    lines.append(f"{'=' * 60}")
    lines.append("")
    lines.append(f"World:       {route['world']}")
    lines.append(f"Distance:    {route['distance']}")
    lines.append(f"Elevation:   {route['elevation']}")
    lines.append(f"Start Route: {route['start_route']}")
    lines.append(f"Strava:      {route['strava']}")
    lines.append("")
    if route.get("description"):
        lines.append(f"Description: {route['description']}")
        lines.append("")
    lines.append(f"{'-' * 40}")
    lines.append("  TURN-BY-TURN DIRECTIONS")
    lines.append(f"{'-' * 40}")
    lines.append("")
    turns = route["turns"]
    explicit = any(turn_has_km(t) for t in turns)
    is_tbd = turns and turns[0].startswith("TBD")
    if not explicit and not is_tbd:
        total_km = parse_distance_km(route["distance"])
        lead_in = route.get("lead_in", 0)
        est = estimate_turn_kms(total_km, len(turns), lead_in)
        if lead_in > 0:
            lines.append(f"  Lead-in: ~{lead_in} km before first turn")
            lines.append("")
        lines.append("  (km values are approximate)")
        lines.append("")
        for i, turn in enumerate(turns):
            m = re.match(r"(\d+\.)\s*(.*)", turn)
            if m:
                num, text = m.groups()
                lines.append(f"  {num:>4s} [{est[i]:>5.1f} km]  {text}")
            else:
                lines.append(f"       [{est[i]:>5.1f} km]  {turn}")
    else:
        for turn in turns:
            lines.append(f"  {turn}")
    lines.append("")
    if route.get("notes"):
        lines.append(f"Notes: {route['notes']}")
        lines.append("")
    lines.append(f"{'=' * 60}")
    lines.append(f"Source: https://zwiftinsider.com/rebel-routes/")
    lines.append(f"{'=' * 60}")
    lines.append("")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filepath


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print(f"Generating {len(ROUTES)} Rebel Route files in: {OUTPUT_DIR}\n")
    for route in ROUTES:
        path = write_route_file(route)
        print(f"  ✓ {os.path.basename(path)}")
    print(f"\nDone! {len(ROUTES)} files created.")


if __name__ == "__main__":
    main()
